travis/.travis.yml
travis/script/functions.sh

For #101. This was first tested out in rspec/rspec-support#148.

Get travis caching to work for bundles of all repos.

---

travis/script/functions.sh

This mirrors the `run_cukes` methodology.

Only run cucumber check when there are features

---

common_markdown_files/CODE_OF_CONDUCT.md

Reframe how to contact maintainers

---

Rakefile

I noticed a small typo and wanted to help fix it.

Fix typo in Rake task description

---

travis/.travis.yml

I do not care to get these anymore. It is easy
enough to check the status and we can see it in
the README with the badge.

Disable emails from travis.

---

travis/.travis.yml

Ruby build matrix updates

---

Rakefile

warn if no ag installed

---

travis/appveyor.yml

Following on from some rspec-core failures I fixed and extracted this.

Update appveyor script for recent changes

---

travis/.travis.yml

Add:
- https://www.ruby-lang.org/en/news/2018/02/24/ruby-2-6-0-preview1-released/
I have the related PR I can open for other repos when this is ok. 
Feel free to make any comments. 🤙🏻

Add CI 2.6.0-preview1

---

travis/.travis.yml

Pin Rubygems to 2.7.8 on older Rubies

---

travis/.travis.yml

From rspec/rspec-rails#2145 applied via:
rspec/rspec-rails#2146
rspec/rspec-mocks#1282
rspec/rspec-expectations#1122
rspec/rspec-core#2646

Pin ubuntu version to allow running older Ruby

---

travis/appveyor.yml

When accepted I will create PR to other repos.

Add Ruby 2.6 to appveyor build

---

travis/.travis.yml

After Jon's comment on https://github.com/rspec/rspec-support/pull/430#discussion_r495807025
Related: https://github.com/rspec/rspec-support/pull/421/commits/548624db45f93676f2d56f134d86d1dc9d6933a6

Follow recommendations and try both diff-lcs version on 2.7.1

---

Rakefile

Removed rspec-rails from being included in sync PRs when `rake travis:create_pr_with_updates` is run.
There is an existing open PR that addresses the same point - https://github.com/rspec/rspec-dev/pull/241 . I have made changes referring to the requested changes mentioned on the above PR.

Rspec-rails no longer needs to be synced with other rspec gems.

---

ci/.github/workflows/ci.yml

Removes unused caching code, and correct run strategy for branches

Follow up for #254

---

ci/.github/workflows/ci.yml
ci/.travis.yml

This is the source of:
rspec/rspec-core#2785
rspec/rspec-expectations#1230
rspec/rspec-mocks#1354
rspec/rspec-support#441

Build updates for JRuby etc

---

Rakefile
ci/.github/workflows/ci.yml

Build changes to allow rspec main builds to configure there own version for rspec-rails

Update RSpec CI flag

---

ci/.github/workflows/ci.yml

Parallel of #266 
https://github.com/rspec/rspec-core/pull/2805
https://github.com/rspec/rspec-expectations/pull/1247
https://github.com/rspec/rspec-mocks/pull/1367
https://github.com/rspec/rspec-support/pull/455

Add 3.0.0-rc1 (for 4-0-dev)

---

ci/.github/workflows/ci.yml

~~Waiting for: https://github.com/ruby/setup-ruby/pull/132~~

Add 3.0.0-rc1

---

common_plaintext_files/.github/FUNDING.yml

As discussed in the mailing list

Add my sponsor account for RSpec

---

common_plaintext_files/CONTRIBUTING.md.erb

See: https://github.com/rspec/rspec-core/pull/2813

Rephrase few parts from contributing doc

---

ci/.github/workflows/ci.yml
ci/.travis.yml
ci/script/cucumber.sh
ci/script/legacy_setup.sh

https://github.com/rspec/rspec-core/pull/2846
https://github.com/rspec/rspec-mocks/pull/1399
https://github.com/rspec/rspec-expectations/pull/1278
https://github.com/rspec/rspec-support/pull/487

Legacy builds for 3-10-maintenance

---

ci/.github/workflows/ci.yml
ci/.travis.yml
ci/script/legacy_setup.sh

Only 1.8.7 to go (which has a weird ffi Issue)
https://github.com/rspec/rspec-core/pull/2853
https://github.com/rspec/rspec-expectations/pull/1280
https://github.com/rspec/rspec-mocks/pull/1403
https://github.com/rspec/rspec-support/pull/488

More legacy rubies

---

ci/.github/workflows/ci.yml
ci/.travis.yml
ci/script/legacy_setup.sh
ci/script/run_build

Same as #283 but for 3-10-maintenance
https://github.com/rspec/rspec-core/pull/2854
https://github.com/rspec/rspec-mocks/pull/1404
https://github.com/rspec/rspec-expectations/pull/1281
https://github.com/rspec/rspec-support/pull/489

More legacy rubies 3 10

---

README.markdown

Hello✋
The original link https://gist.github.com/54177 seemed to be broken, so I fixed the link!

Fix a broken link(README)

---

Gemfile
Rakefile
ci/.github/workflows/ci.yml
ci/script/functions.sh
ci/script/predicate_functions.sh
ci/script/update_rubygems_and_install_bundler

This is #290 rebased for 3-10-maintenance
PRs:
https://github.com/rspec/rspec-core/pull/2901
https://github.com/rspec/rspec-expectations/pull/1308
https://github.com/rspec/rspec-mocks/pull/1430
https://github.com/rspec/rspec-support/pull/509

Dont run rubocop on ruby head 3-10-maintenance

---

Gemfile
Rakefile
ci/.github/workflows/ci.yml
ci/script/functions.sh
ci/script/predicate_functions.sh
ci/script/update_rubygems_and_install_bundler

This is #290 rebased for 4-0-dev
PRs:
https://github.com/rspec/rspec-core/pull/2902
https://github.com/rspec/rspec-expectations/pull/1309
https://github.com/rspec/rspec-mocks/pull/1431
https://github.com/rspec/rspec-support/pull/510

Dont run rubocop on ruby head 4-0-dev

---

ci/.github/workflows/ci.yml

Just pulls commits across from `main` to `3-11-maintenance`

Sync workflows main to 3-11

---

Rakefile
ci/.github/workflows/ci.yml
ci/script/predicate_functions.sh
ci/script/run_build
ci/script/run_rubocop
ci/script/update_rubygems_and_install_bundler

Brings the CI up to date for 4-0-dev

Update CI for 4-0-dev

---

ci/.github/workflows/ci.yml

Source for:
rspec/rspec-core#3056
rspec/rspec-mocks#1560
rspec/rspec-expectations#1442
rspec/rspec-support#588

Add Ruby 3.3 to the matrix

---

Rakefile
ci/script/ci_functions.sh
ci/script/clone_all_rspec_repos
ci/script/functions.sh
ci/script/update_rubygems_and_install_bundler

This is #319 but targetting 3-13-maintenance where it had not been fully cherry picked

Fix clone issue and update bundler

---

ci/.github/workflows/ci.yml

This applies some of the changes from rspec/rspec-core#3086 across the build
rspec/rspec-expectations#1465
rspec/rspec-mocks#1578
rspec/rspec-support#602

Tweak coverage checks for CI

---

ci/.github/workflows/ci.yml

https://github.com/rspec/rspec-core/pull/3099
https://github.com/rspec/rspec-expectations/pull/1469
https://github.com/rspec/rspec-mocks/pull/1580
https://github.com/rspec/rspec-support/pull/604

Fix legacy builds with legacy node 3 13

---

Rakefile
ci/script/predicate_functions.sh

This is #326 but for 3-13-maintenance
https://github.com/rspec/rspec-core/pull/3109
https://github.com/rspec/rspec-expectations/pull/1483
https://github.com/rspec/rspec-mocks/pull/1589
https://github.com/rspec/rspec-support/pull/614

Fix rails build on 3-13-maintenance
