travis/script/functions.sh

This has already been merged into the other repos, but I forgot to open a PR here.

Cleanup bundler args now that all repos are back to using `../bundle`.

---

travis/.travis.yml

travis-ci/travis-ci#3067 has been fixed.

Stop allowing JRuby failures.

---

Rakefile

This adds a command that will regenerate all the YARD docs for rspec.github.io:
``` 
$ bundle exec rake "update_docs[3.2, master]"
$ bundle exec rake "update_docs[3.1, 3-1-maintenance]"
```
Longer term we might want to hook it into the release tasks so the docs are auto-updated but this seemed a good first step.
/cc @JonRowe

Add command to update rspec.github.io docs.

---

README.markdown

@JonRowe here is the section I added to troubleshoot windows issues. Thanks.

Add windows section for troubleshooting purposes

---

travis/.travis.yml
travis/script/functions.sh

This is really only an issue on JRUBY-HEAD where
cext.enabled property no longer exists.
https://travis-ci.org/rspec/rspec-core/jobs/50010459#L166

For discussion: be explicit about JRuby opts

---

travis/.travis.yml

Without this setting, travis runs 2 builds for each
PR that is from a non-fork branch on one of our repos:
one for the HEAD of the branch, plus one for the merge
commit created by GitHub. That’s what the recent
`travis-ci/push` vs `travis-ci/pr` checks we’re seeing are.
Those are extra checks we don’t need that take up extra build
capacity. It’s better to just build commits against the master
and maintenance branches, and any PRs that target those branches.

Whitelist branches for travis.

---

travis/appveyor.yml

We're on a more recent version now so lets remove this.

Remove pinned version of bundler for appveyor

---

Rakefile
common_markdown_files/code_of_conduct.md

This is setup for #124, it adds rake tasks for updating code of conduct files across all rspec repos, and a blank code of conduct file ready for whatever we decide to go with in #124.

Rakefile tasks for code of conduct updates

---

travis/script/functions.sh
travis/script/run_build
travis/script/travis_functions.sh

- Make it work when the other repos are not checked out
in a sibling directory. This ensures that any contributor
can clone the repo and run `script/run_build` and get
the build results for all the parts their local environment
is able to run.
- Provide friendly labels for the parts.
- Move the one-by-one specs part into the `run_build`
script so it is more obvious where in the flow it is.

Improve experience of running `script/run_build` locally.

---

Rakefile
common_markdown_files/BUILD_DETAIL.md.erb
common_markdown_files/CONTRIBUTING.md.erb
common_markdown_files/DEVELOPMENT.md.erb

Start of rspec/rspec-mocks#986.  I'm kinda basing this off of bundler's files.  More to come.

Contributing doc

---

code_of_conduct.md

While not one of the "main" repos, it falls under our "RSpec" umbrella. Adding the CoC to the top level to make it prominent.

Add code of conduct.

---

travis/script/functions.sh
travis/script/run_build

Newer RSpec contributors may not have setup binstubs. When running
`script/run_build` locally it errors in confusing ways. Often at this
point they are unsure how to properly get the binstubs onto the system.
This includes a very simplistic check for the non-optional binstubs. It
aggregates the missing binstubs and the associated gems, then provides
the user helpful options on how to get the binstubs.
While talking with the users it was decided that this is a kinder
approach than simply forcing the creating of the binstubs. Better to
inform the user then forcefully inject executables into their system.

Include a binstubs check before running CI script

---

travis/.rubocop_rspec_base.yml
travis/.travis.yml

This should fix the builds in the other repos.  They've apparently been broken since rspec/rspec-core#2081 was merged due to the introduction of `:ruby_22` in rspec-core's gemfile.

Upgrade bundler

---

Rakefile

This is what was missing from the 3.4 deployment @myronmarston  :/

Manually use ag and sed to replace links

---

code_of_conduct.md

Hello! :wave: 
I wanted to update the github.com/rspec/rspec-support Code of Conduct but when I checked out the file it said not to do so as it is automatically generated and taken from this repository. So, this PR updates your code of conduct to the latest version of the Contributor Covenant.
I don't know which email to add into [INSERT EMAIL ADDRESS HERE], but if you can let me know which address to use I am happy to update it.
Have a fantastic day :rainbow:.

Update COC to latest Contributor Covenant version

---

travis/script/functions.sh
travis/script/predicate_functions.sh

Nokogiri requires Rubygems to be enabled on build.
* https://github.com/sparklemotion/nokogiri/blob/v1.6.7.1/ext/nokogiri/extconf.rb#L396
* https://travis-ci.org/rspec/rspec-expectations/jobs/100053387#L2799

Enable Rubygems on Travis CI

---

travis/script/functions.sh
travis/script/predicate_functions.sh

Turn off rubygems in our normal build process, but use it during `bundle install` for things like `nokogiri` which expect it to be available during the build process. As suggested by @myronmarston as an improvement to @yujinakayama's PR.
rspec/rspec-core#2152
rspec/rspec-mocks#1051
rspec/rspec-expectations#885
rspec/rspec-rails#1521
rspec/rspec-support#263

Only enable rubygems for bundle install

---

travis/appveyor.yml

Version 1.12.0 does not seem to be working properly.
Refs: https://github.com/rspec/rspec-mocks/pull/1080

Force bundler 1.11.2 to be used in Appveyor

---

travis/appveyor.yml

The issue is now fixed upstream, so go back to the old config.

Remove workaround in Appveyor's configuration

---

Rakefile
travis/.travis.yml
travis/appveyor.yml

So it seems Bundler 1.12 is still broken for us, I expect us to be able to remove the version select at some point, but currently we can't install `json` on 2.3.1 on travis, and it also seems to break appveyor with warnings.

Build updates

---

Rakefile

Modify sed to not use backup files (modify in place) when cleaning up
documentation stylesheets/javascript, due to the differences between
gnu sed and OS X sed the command is slightly different on each platform.

Tweak sed command for replacing documentation resources

---

README.markdown

The latest stable version of Ruby is 2.3.1 – it looks like the [`travis.yml` file](https://github.com/rspec/rspec-dev/blob/master/travis/.travis.yml) is already set up to build against it.
I wasn't sure if there was a particular reason this document encourages using version 1.9.3 or if it just went stale. The last version update in the doc seems to have been in 2012 (see https://github.com/rspec/rspec-dev/commit/b00159c6238935f766830f6653cc71ea5e3af494).
Thanks!

Update development setup to use the latest Ruby

---

Rakefile

The latest git command prints "working tree clean" instead of "working directory clean", and `#assert_clean_git_status` fails even when the repo is actually clean.

Make `git clean` check in Rakefile more robust

---

Rakefile
travis/script/predicate_functions.sh
travis/script/run_build

This is for running example_app specs in rspec-rails repo:
* rspec/rspec-rails#1710
* rspec/rspec-rails#1680

Allow running custom additional specs in each repo

---

travis/script/functions.sh

Commit https://github.com/rspec/rspec-core/commit/26dd955abc3bf25a946f6db89c9fb76d2c877c47 was done in rspec-core but it should be done in rspec-dev since the file is auto-generated.

Disable SimpleCov on JRuby

---

travis/.travis.yml

I updated some Ruby version.
And, I think Ruby2.4.1 spec should pass always.

Use latest ruby version in ci

---

travis/.travis.yml

Opposed to what I said in rspec/rspec-core#2444 there is something
we can do, I just underestimated its effect. There is `--dev`
(see https://github.com/jruby/jruby/wiki/Improving-startup-time#use-the---dev-flag).
Locally for the rspec-core --bisect spec this brought the runtime
down from 33 to 36 seconds to 21 seconds!
It also encompasses disabling invoke dynamic already, so no need
for that. It is opposed to server mode that was used however,
server mode targets peak performance at the cost of bigger startup
and warmup times and is usually intended for running on the server/
benchmarks. It was introduced for no reason apparent to me in
bc0b97633ef00 and I think --dev fits the use case better and is
closer to what most peeps probably run either way.
Other changes I did:
* collapsed all …

Better startup times through --dev

---

travis/.travis.yml

We've been used `jruby`, `jruby-head`, `jruby-18mode`, and `jruby-9.1.2.0`, but now they point the following implementations since Travis' recent change:
```
jruby             - JRUBY_VERSION: 9.1.9.0           RUBY_VERSION: 2.3.3
jruby-head        - JRUBY_VERSION: 9.1.10.0-SNAPSHOT RUBY_VERSION: 2.3.3
jruby-18mode      - JRUBY_VERSION: 9.1.7.0           RUBY_VERSION: 2.3.1
jruby-9.1.2.0     - JRUBY_VERSION: 9.1.2.0           RUBY_VERSION: 2.3.0
```
See: https://travis-ci.org/rspec/rspec-support/builds/262713100
So we change them to the followings:
```
jruby             - JRUBY_VERSION: 9.1.9.0           RUBY_VERSION: 2.3.3
jruby-head        - JRUBY_VERSION: 9.1.10.0-SNAPSHOT RUBY_VERSION: 2.3.3
jruby-1.7         - JRUBY_VERSION: 1.7.26            RUBY_VERSION: 1.9.3
jruby-1.7 (--1.8) - …
```

Follow change of JRuby versions on Travis CI

---

travis/.travis.yml

This fixes #184.
The `_JAVA_OPTIONS` environment variable was recently added on Travis but it seems to be problematic.
* https://github.com/travis-ci/travis-ci/issues/8408
* https://superuser.com/questions/585695/suppressing-the-picked-up-java-options-message

Unset _JAVA_OPTIONS env variable on Travis to suppress warning from JVM

---

travis/.travis.yml

Currently it is not running as https://travis-ci.org/rspec/rspec-core/jobs/294537235

Update rubinius reference in Travis CI

---

travis/.travis.yml

…so pin to currently working version

Currently newer versions of JRuby fail to install on Travis via RVM

---

Gemfile
Rakefile

These tasks are currently broken, and were last commited by David 6ish
years ago. There are some other yard references in travis/scripts, but
I'm pretty sure these are only used from within other projects that
themselves declare a yard dependency.
Motivated by CVE in yard.

Remove YARD and related old documentation Rake tasks.

---

travis/.rubocop_rspec_base.yml
travis/script/functions.sh

I disabled all the new layout and style cops, but tried to keep the lint/perf/security ones.
Didn't bother with any kind of sorting/order, couldn't come up with a quick way to do and figured it wouldn't be that valuable.

Update base rubocop config for new version, disabling most of the new things.

---

travis/appveyor.yml

Ruby 1.9.3 is broken on appveyor, not being able to install from Rubygems, as `rubygems` itself isn't tested on Ruby 1.9.3, and it's a sanity check that we work on Windows, lets drop it from the matrix.
See:
rspec/rspec-core#2566
rspec/rspec-mocks#1239
rspec/rspec-expectations#1075
rspec/rspec-support#352
/cc @myronmarston @samphippen

Remove 1.9.3 from appveyor

---

Gemfile

Motivated by
```
/path/to/rake-11.0.1/lib/rake/ext/fixnum.rb:4: warning: constant ::Fixnum is deprecated
```
when running `bundle exec rake git:pull`.

Update rake to current

---

travis/.travis.yml
travis/script/predicate_functions.sh
travis/script/update_rubygems_and_install_bundler

See:
rspec/rspec-core#2589
rspec/rspec-expectations#1094
rspec/rspec-mocks#1255
rspec/rspec-support#362
rspec/rspec-rails#2061

Ensure bundler is pinned to version less than 2.0.0 on older rubies

---

travis/.travis.yml

This PR updates the CI matrix.
- also: Removes an old setting from Travis. See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

CI: use 2.4.6, 2.5.5, 2.6.2

---

README.markdown
Rakefile
code_of_conduct.md
common_plaintext_files/BUILD_DETAIL.md.erb
common_plaintext_files/CODE_OF_CONDUCT.md
common_plaintext_files/CONTRIBUTING.md.erb
common_plaintext_files/DEVELOPMENT.md.erb
travis/script/functions.sh

These were originally supposed to be in #223 but I forgot to push, they've already been updated or extracted from the repos, we had not kept these up to date.

Markdown file consistency

---

README.markdown

Close: #46 
I am not sure this is what was expected, but this is a first draft.
I didn't add https://github.com/rspec/rspec-autotest because it doesn't seems maintained/used anymore. @JonRowe you probably knows if we should add it.
Have a nice day.

List more rspec gems in README

---

travis/script/predicate_functions.sh

Previously, `rspec-rails` compat specs were run against Rails 5, and some of them, specifically ActionCable ones, are only present and run for Rails 6.
This change makes sure `rspec-core`/`rspec-mocks`/`rspec-expectations`/`rspec-support` changes don't break `rspec-rails`'s newer features.
Changes from `ruby_23_plus` to `ruby_25_plus` is required since Rails 6 requires Ruby 2.5+ (compared to 2.2.2+ for Rails 5).
https://github.com/rspec/rspec-support/pull/398
https://github.com/rspec/rspec-core/pull/2691
https://github.com/rspec/rspec-expectations/pull/1159
https://github.com/rspec/rspec-mocks/pull/1314
~https://github.com/rspec/rspec-rails/pull/2269~ - not needed
Related update to use Rails 6 when running specs by default https://github.com/rspec/rspec-rails/pull/2267 (*merged*)
Proof …

Update scripts to run compat specs against Rails 6

---

common_plaintext_files/CONTRIBUTING.md.erb

Following [this comment from @JonRowe](https://github.com/rspec/rspec-expectations/pull/1156#issuecomment-578391876). I thought it will be a good idea to add documentation about how to contribute to multiple RSpec gems at the same time.

Add documentation about multi gems contribution flow

---

Rakefile

Related to : https://github.com/rspec/rspec.github.io/pull/131
Each documented RSpec gem have `.yardopts`. The previous was code was using same `../.yardopts` but we want to use specific `yardopts` from each repo.
`rspec-rails` have specific `--exclude` rules for example.
```sh
rspec-dev/ $ find . -iname '.yardopts' -maxdepth 3
./repos/rspec-mocks/.yardopts
./repos/rspec-expectations/.yardopts
./repos/.yardopts
./repos/rspec-core/.yardopts
./repos/rspec-rails/.yardopts
```

Use .yardopts from each repo when generating documentation

---

travis/script/predicate_functions.sh

Yard 0.9.21 support Ruby 2.7 now.
https://github.com/lsegal/yard/releases/tag/v0.9.21
This reverts commit 30859b562aa04ca5e3a646b7ee79a36445378706.
Close: https://github.com/rspec/rspec-dev/issues/232

Revert "Prevent rubydoc check running on 2.7.0"

---

Rakefile

* Remove rspec-doc-template yard plugin. Impact: https://github.com/rspec/rspec.github.io/pull/138
* Remove empty lines generated by rdoc/erb. Impact: https://github.com/rspec/rspec.github.io/pull/139 ⚠️
Related:
- https://github.com/rspec/rspec-rails/pull/2298#discussion_r400436204

Remove rspec-doc-template yard plugin + remove empty lines from HTML doc

---

Rakefile

This commit is the answer to https://github.com/rspec/rspec.github.io/pull/138#discussion_r404694077
To avoid having documentation with unreleased changes, we stick to the commit of the last release of the MAJOR.MINOR version.  
With: `bundle exec rake "update_docs[3.9, 3-9-maintenance]"`
args[:version] will be 3.9. The command will search for the latest tag
that match 3.9, for example v3.9.2

Stick to last commit from a release when generating new documentation

---

Rakefile

I love when we can easily get initial PR when generating PR from rspec-dev. This change add the ability to generate pull request with an additionnal comment.
For example: 
```sh
bundle exec rake "travis:create_pr_with_updates[https://github.com/rspec/rspec-dev/pull/233]"
```
Generates
You can also use:
```
$ bundle exec rake 'common_plaintext_files:create_pr_with_updates[Generated from: https://github.com/rspec/rspec-dev/pull/230]'
```
Will generate pull request with body:
```md
These are some updates, generated from rspec-dev's rake tasks.
Generated from: https://github.com/rspec/rspec-dev/pull/230
```
If no extra comment provided, we simply use this body:
```md
These are some updates, generated from rspec-dev's rake tasks.
```

Be able to refer to pull request from rspec-dev in each rspec gems PR

---

Rakefile

With this PR:
- Generate documentation for every last release when they are available. It means we can generate documentation for `rspec-rails` 4 with this code without generating other gems at the moment.
- Fix a bug by not choosing beta or release candidate version like `v4.0.0.rc1`
- Handle major branch change with various `Gemfile` variations. Avoid error like:
---
For example with:
```sh
$ bundle exec rake "update_docs[4.0, 4-0-maintenance]"
```
We only have rspec-rails with a v4.0.0 version at the moment, so the command will generate documentation only for `rspec-rails` 4.0 documentation, other rspec gem will be skipped.
If we run:
```sh
$ bundle exec rake "update_docs[3.9, 3-9-maintenance]"
```
Every last 3.x release version of documented rspec gems will have their
documentation …

Be able to generate doc for rspec-rails 4

---

travis/.travis.yml

Hello
https://www.ruby-lang.org/en/news/2020/09/25/ruby-3-0-0-preview1-released/
I choose to be very explicit. `rvm use 3.0.0-preview1` was not working, `rvm use 3` yes but I think we should be explicit when we speak about version. :) 
Have a nice evening

Add Ruby3 preview1 to build matrix with allow_failures

---

travis/.travis.yml

It is already green on CI for core, mocks, support and expectations. 🙌🏻

Do not allow failures with Ruby 3.0.0-preview1

---

Rakefile

I used this with a bit of manual help to create the `4-0-dev` branches, committing here for future use.

Helper to update version branches like 4-0-dev

---

common_plaintext_files/BUILD_DETAIL.md.erb
common_plaintext_files/DEVELOPMENT.md.erb

These changes are from rspec/rspec-expectations which were reverted by rspec/rspec-expectations#1254
They should probably be applied to all repos?

Updates to Rubocop instructions

---

Rakefile
ci/.github/workflows/ci.yml
ci/script/predicate_functions.sh
ci/script/run_build

Skip our cross build checks on ruby-head, we only need to not run rspec-rails really, but I feel we should focus only on each repo on ruby-head, its going to break at various points anyway (likely) so running a  minimal compatibility check feels better.
https://github.com/rspec/rspec-core/pull/2821
https://github.com/rspec/rspec-expectations/pull/1257
https://github.com/rspec/rspec-mocks/pull/1375
https://github.com/rspec/rspec-support/pull/467

Fix ruby head

---

Rakefile
ci/.github/workflows/ci.yml
ci/script/predicate_functions.sh
ci/script/run_build
common_plaintext_files/.github/FUNDING.yml
common_plaintext_files/BUILD_DETAIL.md.erb
common_plaintext_files/CONTRIBUTING.md.erb
common_plaintext_files/DEVELOPMENT.md.erb

Brings CI and Markdown in line with `main`

Updates from main

---

Rakefile
ci/.github/workflows/ci.yml

Identical to #275 but for 4-0-dev.

Improve project helpers (based off 4-0-dev)

---

Rakefile

Allows an override of `ONLY="project names"` and `EXCEPT="project names"` (delimited by space) for working with the multi repo scripts. This was useful when working with files for `4-0-dev` and markdown files.

Improve project helpers

---

ci/script/run_build

Sometimes coverage is not consistent across builds for no apparent reason. E.g.:
cross-build https://github.com/rspec/rspec-support/runs/1626127309
```
Coverage report generated for RSpec to /home/runner/work/rspec-support/rspec-expectations/coverage. 3116 / 3596 LOC (86.65%) covered.
```
vs local spec run:
```
2793 relevant lines, 2763 lines covered and 30 lines missed. ( 98.93% ) 
```
vs branch build https://github.com/rspec/rspec-expectations/runs/1626068228?check_suite_focus=true:
```
Coverage report generated for RSpec to /home/runner/work/rspec-expectations/rspec-expectations/coverage. 2905 / 3059 LOC (94.97%) covered.
```
See:
- https://github.com/rspec/rspec-support/runs/1626127309
- https://github.com/rspec/rspec-support/pull/477#issuecomment-752517985
Sub-builds:
- …

Skip coverage checks for cross-builds

---

ci/.github/workflows/ci.yml

It seems to be impossible to:
- get rid of the whole section due to subsequent env: ${{ matrix.env }}
- use []
- use {}
- use - with no vars
Follow-up fix to:
- https://github.com/rspec/rspec-support/pull/477
- https://github.com/rspec/rspec-core/pull/2833
- https://github.com/rspec/rspec-expectations/pull/1268
- https://github.com/rspec/rspec-mocks/pull/1384
Sub-prs:
- https://github.com/rspec/rspec-core/pull/2837
- https://github.com/rspec/rspec-expectations/pull/1273
- https://github.com/rspec/rspec-mocks/pull/1389
- https://github.com/rspec/rspec-support/pull/480

Remove diff-lcs default env var

---

ci/.github/workflows/ci.yml

From https://github.com/rubygems/rubygems/issues/4228#issuecomment-825184822
Fixes legacy builds

Update legacy rubygems ip

---

Gemfile
Rakefile
ci/.github/workflows/ci.yml
ci/script/functions.sh
ci/script/predicate_functions.sh
ci/script/update_rubygems_and_install_bundler

Originally this PR started as a need to skip rubocop on ruby head as it was failing our builds.
It was extended to update some dependencies for Ruby 3.x, to allow a more consistent "force" approach for updating PRs and  added a pinned bundler version to work around rubygems/rubygems#4754 
PRs:
https://github.com/rspec/rspec-core/pull/2900
https://github.com/rspec/rspec-expectations/pull/1307
https://github.com/rspec/rspec-mocks/pull/1429
https://github.com/rspec/rspec-support/pull/508

Dont run rubocop on ruby head

---

ci/.github/workflows/ci.yml

This is a trivial update, but it's the latest version.

CI: Update GitHub Action checkout to v3

---

ci/.github/workflows/ci.yml

This just locks down all our repo's permissions as per rspec/rspec-core#2966

Set CI permissions to read-only

---

ci/.github/workflows/ci.yml

This PR ensures that only the last execution per branch always works, even when pushed multiple times in a row, for example. The older one is canceled.
I find myself pushing often, and with many jobs the GHA limit them to a certain amount of concurrently running jobs.
This limit is applied per-org, so if there's a running rspec-rails build means the rspec-core build jobs will spin in a queued state until the first build jobs start to release job slots.
Refs:
- https://docs.github.com/en/actions/using-jobs/using-concurrency
- https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
Credit for this feature that went under my radar goes to @ydah

Limit GHA to one active build per workflow/branch

---

Rakefile

We run double the builds on updates from `rspec-dev` for maintenance branches
```
RSpec CI / Ruby 3.1 (pull_request) Successful in 4m
RSpec CI / Ruby 3.1 (push) Successful in 6m
```
[Example](https://github.com/rspec/rspec-core/pull/3000):
due to branch naming (`update-ci-build-scripts-2023-01-11-for-3-12-maintenance`) that falls under this rule:
```
on:
push:
branches:
- 'main'
- '*-maintenance'
- '*-dev'
```

Change the branch name format

---

ci/.github/workflows/ci.yml

Docker hub is removing free plans so move our containers to GHCR.

Switch docker builds to Github container registry.

---

Rakefile
common_plaintext_files/BUILD_DETAIL.md.erb
common_plaintext_files/CONTRIBUTING.md.erb

Removes Relish references from common markdown:
- rspec/rspec-core#3033
- rspec/rspec-expectations#1418
- rspec/rspec-mocks#1544
- rspec/rspec-support#576

Remove Relish references

---

Rakefile
common_plaintext_files/BUILD_DETAIL.md.erb
common_plaintext_files/CONTRIBUTING.md.erb

Removes Relish references from common markdown file for 3-12-maintenance
- rspec/rspec-core#3034
- rspec/rspec-expectations#1419
- rspec/rspec-mocks#1545
- rspec/rspec-support#577

Remove relish from 3-12-maintenance

---

ci/.github/workflows/ci.yml

Inspired by dependabot, but leaving the legacy build alone, merged in:
rspec/rspec-core#3048
rspec/rspec-expectations#1431
rspec/rspec-mocks#1555
rspec/rspec-support#585

Upgrade checkout to v4 where possible

---

Rakefile
ci/.github/workflows/ci.yml
ci/script/clone_all_rspec_repos
common_plaintext_files/ISSUE_TEMPLATE.md.erb

A bunch of changes from main rebased off 3-12 to fix builds.
Source of:
rspec/rspec-core#3060
rspec/rspec-expectations#1445
rspec/rspec-mocks#1563
rspec/rspec-support#590

Sync 312 to current

---

README.markdown
Rakefile

This PR updates the README documentation to:
1. Identify `the_silver_surfer` as a required package (since the error only identifies the binary name "ag" which is too short to be accurately googled and has a Ruby gem by the same name that is not the right thing)
2. Identify that users will need to fork all repositories used by `rspec-dev` based on how it looks up the URL (since otherwise they are just faced with repository not found errors). 
3. Update the Rakefile to reflect the new name of the `rspec-metagem` repository. If a user is forking all the repositories to make this repo work, then they won't have the `rspec`->`rspec-metagem` redirect set up and will need to pull it from the proper name.
Feel free to not merge this pull request if it is not in line with your project's direction. …

Updated documentation to reflect current requirements and package names

---

ci/.github/workflows/ci.yml

https://github.com/rspec/rspec-core/pull/3098
https://github.com/rspec/rspec-expectations/pull/1468
https://github.com/rspec/rspec-mocks/pull/1579
https://github.com/rspec/rspec-support/pull/603

Allow legacy builds to use older node

---

ci/script/functions.sh

Sideload a fix for cucumber on ruby-head, as there is a change to hash behaviour imcompatible with the current version.
Relevant PRs:
https://github.com/rspec/rspec-core/pull/3102
https://github.com/rspec/rspec-expectations/pull/1474
https://github.com/rspec/rspec-mocks/pull/1582
https://github.com/rspec/rspec-support/pull/608

Add workaround for cucumber on ruby-head

---

ci/script/functions.sh

This is #324 but for 3-13-maintenance
Relevant PRs:
https://github.com/rspec/rspec-core/pull/3103
https://github.com/rspec/rspec-expectations/pull/1475
https://github.com/rspec/rspec-mocks/pull/1583
https://github.com/rspec/rspec-support/pull/609

Add workaround for cucumber

---

Rakefile
ci/script/predicate_functions.sh

RSpec Rails 7.0.0 changed its minimum supported Ruby in line with Rails itself, so we need to fix that, but we can also relax a previous constraint which was fixed.
https://github.com/rspec/rspec-core/pull/3108
https://github.com/rspec/rspec-expectations/pull/1482
https://github.com/rspec/rspec-mocks/pull/1588
https://github.com/rspec/rspec-support/pull/613

Fix rails build
